### ISSUE TITLE
Curious why my account was auto-kicked upon joining? (Same acct name, had joined via riot.im/matrix app on iOS)

### ISSUE THREAD

**Issue by netluxe** [linuxmasterrace/IRC-Rules#3]

**Comment by Volkor3-16** [comment]
I'm not exactly sure, but the matrix bridge has always caused some issues with the IRC channel, so you might have to register with NickServ before joining. (/msg NickServ HELP) (and then log in with nickserv every time the bridge disconnects

If you can't get it working, join the IRC using kiwiirc and ping a Operator (@ before their name)

http://webchat.snoonet.org/linuxmasterrace
